a,b,c,d=int(input()),int(input()),int(input()),int(input())
print(a==c or b==d)
print(abs(a-c)==abs(b-d))
print(abs(a-c)<=1 and abs(b-d)<=1)
print((a==c or b==d) or abs(a-c)==abs(b-d))
print(a==c and d-b==1)
print(abs(a-c)==1 and d-b==1)
print(a==c and b-d==1)
print(abs(a-c)==1 and b-d==1)
print((abs(a-c)==2 and abs(b-d)==1) or (abs(a-c)==1 and abs(b-d)==2))